# Fast model - 빠른 추론 속도
name: "fast_model"
description: "실시간 처리용 경량 모델"

backbone:
  type: convnext_fpn
  model_name: tiny
  pretrained: true
  fpn_channels: 256
  use_fpn: false  # FPN 비활성화로 속도 향상

blade_head:
  in_channels: 256
  num_classes: 2
  dropout_rate: 0.0  # 드롭아웃 제거

damage_head:
  in_channels: 256
  num_classes: 3
  use_soft_gating: false  # 단순 마스킹
  boundary_margin: 5

training:
  freeze_backbone: true  # 백본 고정으로 학습 속도 향상
  freeze_blade_head: true
  blade_checkpoint: "best_unified_blade_model.pth"
  damage_checkpoint: null