# Best performance model - 최고 성능
name: "best_performance_model"
description: "최고 정확도를 위한 대형 모델"

backbone:
  type: convnext_fpn
  model_name: small  # 더 큰 백본
  pretrained: true
  fpn_channels: 256
  use_fpn: true

blade_head:
  in_channels: 256
  num_classes: 2
  dropout_rate: 0.1

damage_head:
  in_channels: 256
  num_classes: 3
  use_soft_gating: true
  boundary_margin: 15  # 더 넓은 마진

training:
  freeze_backbone: false
  freeze_blade_head: false  # 전체 fine-tuning
  blade_checkpoint: "best_unified_blade_model.pth"
  damage_checkpoint: null