# Augmented data configuration
name: "augmented_data"
description: "강한 증강 설정"

# default.yaml 상속
inherit_from: "configs/data_configs/default.yaml"

augmentation:
  train:
    # 기본 증강 + 추가
    random_rotate:
      prob: 0.7  # 증가
      degrees: [-180, 180]
    
    # 새로운 증강 추가
    random_crop:
      prob: 0.3
      scale: [0.8, 1.0]
    
    color_jitter:
      prob: 0.4
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.1
    
    random_erasing:
      prob: 0.2
      scale: [0.02, 0.1]
    
    mixup:
      prob: 0.2
      alpha: 0.2
    
    cutmix:
      prob: 0.2
      alpha: 1.0