# Unified model training (both heads)
name: "unified_training"
description: "통합 모델 전체 학습 설정"

model:
  config_file: "configs/model_configs/balanced.yaml"
  freeze_blade_head: false  # 처음엔 true, 나중에 false

data:
  root_path: "C:/EngineBladeAI/EngineInspectionAI_MS/data"
  blade_data_path: "blade_data"
  damage_data_path: "multilabeled_data_augmented"
  batch_size: 4
  num_workers: 4
  augmentation:
    rotation: true
    flip: true
    blur: true
    brightness: true
    contrast: true
    mixup: false
    cutmix: false

optimizer:
  type: "AdamW"
  lr: 5e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]
  different_lr:
    backbone: 1e-5
    blade_head: 5e-5
    damage_head: 1e-4

scheduler:
  type: "OneCycleLR"
  max_lr: 1e-4
  epochs: 40
  pct_start: 0.1
  anneal_strategy: "cos"

training:
  epochs: 40
  gradient_clip: 1.0
  mixed_precision: true
  accumulate_grad_batches: 2
  
  # 2-stage training
  stage1:
    epochs: 20
    freeze_blade: true
    focus: "damage"
  
  stage2:
    epochs: 20
    freeze_blade: false
    focus: "both"
  
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor: "val_combined_score"

loss:
  blade:
    type: "CrossEntropyLoss"
    weight: 1.0
  damage_segmentation:
    type: "CrossEntropyLoss"
    weight: 1.0
  damage_multilabel:
    type: "BCELoss"
    weight: 2.0
  total_weight_blade: 1.0
  total_weight_damage: 1.5

validation:
  val_interval: 1
  metrics:
    - "blade_iou"
    - "damage_f1"
    - "damage_map"
    - "combined_score"

logging:
  log_interval: 10
  save_interval: 5
  tensorboard: true
  wandb: true
  project_name: "EngineBladeInspection"
  save_best_only: true
  save_last: true